# Generated by Django 4.0.5 on 2022-07-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos', verbose_name='Archivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created'],
            },
        ),
    ]
