# Generated by Django 4.0.5 on 2022-07-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
